### ISSUE TITLE
On trying to load library: .onAttach failed in attachNamespace()

### ISSUE THREAD

**Issue by seanthimons** [pepijn-devries/ECOTOXr#44] opened 2024-12-10 19:25 UTC
Version 1.1.1, from both CRAN and dev version. 
`library(ECOTOXr)`
`Loading required package: RSQLite`
`Error: package or namespace load failed for ‘ECOTOXr’:`
`.onAttach failed in attachNamespace() for 'ECOTOXr', details:`
 `call: if (any(nchar(file_reg) > 0)) {`
`error: missing value where TRUE/FALSE needed`

**Comment by pepijn-devries** [comment] 2024-12-19 11:32
As I suspect that this is a local issue and is not caused by the package I'm closing this issue. Please reopen if you can provide a reproducible example of the issue.

**Closed by pepijn-devries** 2024-12-19 11:32 UTC

**Comment by seanthimons** [comment] 2025-02-04 20:28
Hi @pepijn-devries 

Apologies for extremely late reply. 

Even forcing dependencies + imports to be included, error persists. 

Session Info: 

> devtools::session_info()
─ Session info ────────────────────────────────────────────────
 setting  value
 version  R version 4.4.2 (2024-10-31 ucrt)
 os       Windows 11 x64 (build 22631)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2025-02-04
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cachem        1.1.0   2024-05-16 [1] CRAN (R 4.4.2)
 cli           3.6.3   2024-06-21 [1] CRAN (R 4.4.2)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.4.2)
 digest        0.6.37  2024-08-19 [1] CRAN (R 4.4.2)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.4.2)
 fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.4.2)
 fs            1.6.5   2024-10-30 [1] CRAN (R 4.4.2)
 glue          1.8.0   2024-09-30 [1] CRAN (R 4.4.2)
 htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.2)
 htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.4.2)
 httpuv        1.6.15  2024-03-26 [1] CRAN (R 4.4.2)
 later         1.4.1   2024-11-27 [1] CRAN (R 4.4.2)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.2)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.4.2)
 mime          0.12    2021-09-28 [1] CRAN (R 4.4.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.4.2)
 pkgbuild      1.4.6   2025-01-16 [1] CRAN (R 4.4.2)
 pkgload       1.4.0   2024-06-28 [1] CRAN (R 4.4.2)
 profvis       0.4.0   2024-09-20 [1] CRAN (R 4.4.2)
 promises      1.3.2   2024-11-28 [1] CRAN (R 4.4.2)
 purrr         1.0.2   2023-08-10 [1] CRAN (R 4.4.2)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.4.2)
 Rcpp          1.0.14  2025-01-12 [1] CRAN (R 4.4.2)
 remotes       2.5.0   2024-03-17 [1] CRAN (R 4.4.2)
 rlang         1.1.5   2025-01-17 [1] CRAN (R 4.4.2)
 rstudioapi    0.17.1  2024-10-22 [1] CRAN (R 4.4.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.2)
 shiny         1.10.0  2024-12-14 [1] CRAN (R 4.4.2)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.4.2)
 usethis       3.1.0   2024-11-26 [1] CRAN (R 4.4.2)
 vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.4.2)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.4.2)

 [1] C:/Users/STHIMONS/AppData/Local/Programs/R/R-4.4.2/library

Traceback: 

> traceback()
6: stop(msg, call. = FALSE, domain = NA)
5: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch({
       attr(package, "LibPath") <- which.lib.loc
       ns <- loadNamespace(package, lib.loc)
       env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
   }, error = function(e) {
       P <- if (!is.null(cc <- conditionCall(e))) 
           paste(" in", deparse(cc)[1L])
       else ""
       msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
           sQuote(package), P, conditionMessage(e))
       if (logical.return && !quietly) 
           message(paste("Error:", msg), domain = NA)
       else stop(msg, call. = FALSE, domain = NA)
   })
1: library(ECOTOXr)

**Comment by pepijn-devries** [comment] 2025-02-05 08:38
Hi @seanthimons ,

It is still not much to go on. The traceback does not seem to offer any hints. It just tells us that it failed to load the namespace of the package.

The only thing I can think of is that the package shows a message upon attaching, informing the user whether a local database is present or not. I've prepared a branch where this startup message is skipped. Could you test if you can load that version? You can install it with
```r
remotes::install_github("pepijn-devries/ECOTOXr@attach-test")
```

**Comment by pepijn-devries** [comment] 2025-02-05 08:41
By the way, I don't think that RSQLite is the problem. Does that library load when simply calling `library(RSQLite)`?

**Comment by seanthimons** [comment] 2025-02-05 16:54
> Hi [@seanthimons](https://github.com/seanthimons) ,
> 
> It is still not much to go on. The traceback does not seem to offer any hints. It just tells us that it failed to load the namespace of the package.
> 
> The only thing I can think of is that the package shows a message upon attaching, informing the user whether a local database is present or not. I've prepared a branch where this startup message is skipped. Could you test if you can load that version? You can install it with
> 
> remotes::install_github("pepijn-devries/ECOTOXr@attach-test")

This worked! I did some further digging by checking the cache location. It looks like that when the download fails or is interrupted, the incomplete file (or a file of size 0kb) seems to prevent the check for a valid database on loading.

**Comment by pepijn-devries** [comment] 2025-02-05 18:24
Glad to hear that this fixed the issue. I guess I have to make the check more robust...
